### ISSUE TITLE
Add exclude directory/files option

### ISSUE THREAD

**Issue by igoragatti** [Inf166/action-sshpass-rsync#3]
Example if I wanted to run something of the sort:

rsync SRC/FOLDER/ DEST/FOLDER/ -rvz --delete --exclude='wp-content/uploads/'

**Comment by mai-space** [comment]
Sorry for the late reply - I was busy working on my bachelor thesis. I will look into this

**Comment by mai-space** [comment]
@igoragatti I hope the latest release v2.2 fixes your problem :)
